### ISSUE TITLE
Android 6,7,8

### ISSUE THREAD

**Issue by theavijitsarkar** [RashadSaleh/cordova-check-mock-locations-enabled-plugin#1]
Doesnt support android 6 and up

**Comment by RashadSaleh** [comment]
Hey @snowbreeze. Please check [this fork](https://github.com/husmen73/cordova-check-mock-locations-enabled-plugin) which adds support for API Level 23. You might find that it works beyond that, though, since the major difference between Android 5 and Android 6 is the way the user gives permissions. I honestly do not need this plugin anymore in my project so most probably I won't continue its development. However, the code is really very, very short and perhaps any changes to be made to support 7 and up would be minor; so feel free to dig into the source code and good luck!

**Comment by theavijitsarkar** [comment]
Thank you for the support
